### ISSUE TITLE
allowing pidfile location override

### ISSUE THREAD

**Issue by jpeyret** [sous-chefs/nginx#460]
### Cookbook version
8.1.2

### Chef-client version
chef-client version: 13.4.19

### Platform Details
Ubuntu 16.04.3 LTS

### Steps to Reproduce:
`/bin/systemctl --system reload nginx` 

has an error when run manually (originally from *monit*)

### Expected Result:
clean execution without errors.

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

`STDERR: Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.`

running `systemctl status nginx.service` gives:

````
Jun 23 11:41:13 vagrant nginx[21846]: nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory)
````

Now, there is a lot of verbiage around `nginx` and `systemd,` such as [https://www.cloudinsidr.com/content/heres-fix-nginx-error-failed-read-pid-file-linux/](https://www.cloudinsidr.com/content/heres-fix-nginx-error-failed-read-pid-file-linux/).  

I do not think that the error via this Chef install is **directly** caused by this issues however, because the pidfile location is incorrect and when I fixed it, everything went well.

Details:

What got my attention was that, when I looked at systemd's config for nginx, I saw:

````
root@vagrant:~# systemctl show -p FragmentPath nginx.service

FragmentPath=/lib/systemd/system/nginx.service 

root@vagrant:~# egrep Service  -A 10 --no-filename /lib/systemd/system/nginx.service

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t -q -g 'daemon on; master_process on;'
ExecStart=/usr/sbin/nginx -g 'daemon on; master_process on;'
ExecReload=/usr/sbin/nginx -g 'daemon on; master_process on;' -s reload
ExecStop=-/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid
TimeoutStopSec=5
KillMode=mixed

[Install]
````

Which matches what I see in the file system:

````
root@vagrant:/run# realpath nginx.pid
/run/nginx.pid
````

Now, the problem seems to be that `nginx-8.1.2/libraries/helpers.rb`, under my conditions (I initially did not provide any overrides to the cookbook attributes), assumes that it will be `/var/run/nginx.pid`.  I saw your note that figuring out the location is hard to do in all cases.

So, why not allow the user to override the location?  It won't help with getting the pidfile location right by default, but it should help when it needs to be fixed.

####my `attributes/default.rb`.

`override['nginx']['pidfile_location'] = "/run/nginx.pid"`

#### and my modifications to `helpers.rb`.

````
# simple helper module for the nginx cookbook
module NginxRecipeHelpers
  # pidfile is hard to determine on Debian systems.
  # Upstream packages and older distro releases use '/var/run/nginx.pid'
  # systemd based distros and Ubuntu 14.04 use '/run/nginx.pid' for their
  # packages
  def pidfile_location

   #this is the proposed change - use a pidfile_location, if specified.  else do as before.
    if (!node['nginx']['pidfile_location'].nil?) then
      node['nginx']['pidfile_location']

    elsif (node['nginx']['repo_source'].nil? || %w(distro passenger).include?(node['nginx']['repo_source'])) &&
       (node['init_package'] == 'systemd' || node['platform_version'].to_f == 14.04)
     #end of changes.


      '/run/nginx.pid'
    else
      '/var/run/nginx.pid'
    end
  end
end


````

**Comment by damacus** [comment]
Unless someone would like to make a PR for this feature, it's not something we're looking to support in the near term.
