### ISSUE TITLE
Cookbook readme indicates that configure_flags is deprecated but it is used in nginx.conf.erb template

### ISSUE THREAD

**Issue by virtuman** [sous-chefs/nginx#463]
### Cookbook version
8.1.5

### Chef-client version
12.x

### Platform Details
centos baremetal

### Scenario:
nginx.conf.erb depends on deprecated variable

deprecation notice can be found here: 
https://github.com/chef-cookbooks/nginx#nginxsource

and the line referencing deprecated variable:
https://github.com/chef-cookbooks/nginx/blob/master/templates/default/nginx.conf.erb#L122

### Expected Result:
it should probably use `['default_configure_flags'].include?` for proper behavior

**Comment by damacus** [comment]
This should be fixed in the latest release. If this isn't the case please reopen! 

Thanks,
Dan
