### ISSUE TITLE
Get the build passing

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/nginx#489]
# Brief Description

As of 2019-03-18, the build is not passing in CircleCI:

https://circleci.com/gh/sous-chefs/nginx

We need this to be remedied before we can really make headway on the existing open PRs

## Cookbook version

HEAD, 2019-03-18

## Chef-client version

N/A

## Platform Details

CircleCI

## Scenario

...

## Steps to Reproduce

Go to https://circleci.com/gh/sous-chefs/nginx, check latest build

## Expected Result

Successful build

## Actual Result

Failed Build

**Comment by josephholsten** [comment]
Looks like there isn't even a build for the `master` branch. PDI.

**Comment by damacus** [comment]
We did it! 🎉
