### ISSUE TITLE
Export default values

### ISSUE THREAD

**Issue by salsa-dev** [sous-chefs/nginx#503]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

Usage of the default values (like nginx_dir) can be made more flexible.

## :grey_question: Possible Solution

create `libraries/default_values.rb`
within the namespace `Nginx::Cookbook::Defaults`
that can be used in custom cookbooks to get the defaults like `Nginx::Cookbook::Defaults.nginx_dir`

**Comment by MarkGibbons** [comment]
Where would you want to use the default values?  "Custom cookbooks" sort of implies you might want to use the values in a recipe.  Attributes/methods like nginx_dir are already available in Nginx::Cookbook::Helpers, but they are not pushed to the Recipe DSL.

**Comment by bmhughes** [comment]
As far as I can tell this doesn't apply to the v11 refactor, so closing this.
