### ISSUE TITLE
Can't define server_names_hash_bucket_size

### ISSUE THREAD

**Issue by Lasering** [sous-chefs/nginx#507]
## Brief Description
The nginx cookbook can't handle extra configs to nginx.conf, namely server_names_hash_bucket_size.

A property named `conf_variables` does exist for the `nginx_install` and the `nginx_config` however it does nothing.

## Cookbook version
Version 10.0.1

Also see #504

**Comment by MarkGibbons** [comment]
Documentation updates in #550.
