### ISSUE TITLE
Support for pre-v10 attributes

### ISSUE THREAD

**Issue by piloos** [sous-chefs/nginx#530]
## :ghost: Brief Description

In release 10, the cookbook switched from being _attributes_ based to being _resource_ based.  How do we support configuration options (eg. `client_max_body_size`) which are not present in the resource?  It seems that the only way is to create your own `nginx.conf` template which seems cumbersome and error prone: suddenly we need to specify _all_ nginx parameters and support the configuration file for newer versions of nginx
Am I missing something in the philosophy of the _attributes_ vs _resource_ switch?

## :pancakes: Cookbook version

10.0.2

## :woman_cook:  Chef-Infra Version

15.6.10

## :tophat: Platform details

Ubuntu 16.04

**Comment by damacus** [comment]
This looks like a feature request, where we just need to add that property to the resource. We should be covering it, if it's a highly used one (max_body_size seems like it should be!) 

If you want to get a list together, we can add a bunch to a PR and get this fixed. Better yet, feel free to open a PR with docs and the feature and it'll get shipped! 


The latter is more likely to happen as I'm currently rewriting Java, and we could always use more contributions! 


Thanks,
Dan

**Comment by damacus** [comment]
I'm going to close this one down for a more focused feature request. If anyone wants a
