### ISSUE TITLE
NGINX: Stream directories and scripts

### ISSUE THREAD

**Issue by fluxX04** [sous-chefs/nginx#537]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The stream module was removed with this [commit ](https://github.com/sous-chefs/nginx/commit/b7b9326b43b30cc97fc25b269fd1ff9de8dca33f) but folders and scripts are getting still created.  

https://github.com/sous-chefs/nginx/blob/master/resources/install.rb#L265-L266  
https://github.com/sous-chefs/nginx/blob/master/resources/install.rb#L287-L288

## :pancakes: Cookbook version

newest: 10.0.2

## :police_car: Expected behavior

Don't create those directories and scripts or do i have missed something?

Greetz

**Comment by damacus** [comment]
Nope they shouldn't be created. Feel free to tidy that one up!
