### ISSUE TITLE
Purpose of the log resource on install

### ISSUE THREAD

**Issue by fluxX04** [sous-chefs/nginx#538]
Hello,

what's the purpose of the log resource on the installation when installing NGINX from distro or other repos/sources?
https://github.com/sous-chefs/nginx/blob/master/resources/install.rb#L173  

We are monitoring the updates what chef does and everytime 2 resources are getting updated because of the log line.  
`Chef Infra Client finished, 2/207 resources updated in 12 seconds`

Greetz

**Comment by damacus** [comment]
Hey there, thanks for opening an issue. 

This looks like a small bug in the resource. This should probably only log out, if we're on the `:info`  level of the Chef run output. 

That should be a pretty easy fix. Would you mind submitting a patch? 

[Here's a link to the log docs to get you started](https://docs.chef.io/resources/log/)

**Comment by fluxX04** [comment]
Hey,

unfortunately i didn't tested my changes, and after upgrading to the newest version the log gets still executed.

My change didn't made any changes because the default value of `level` property is already `:info`.
Should the `level` be changed to `:debug` instead?

Greetz
