### ISSUE TITLE
Follow up for logging issue #538

### ISSUE THREAD

**Issue by fluxX04** [sous-chefs/nginx#543]
Hey,

unfortunately i didn't tested my changes in PR #541 and after upgrading to the latest version the log gets still executed because the default value of the [level property](https://docs.chef.io/resources/log/#properties) is already `:info`.
Should this be changed to `:debug` instead?

Greetz

**Comment by MarkGibbons** [comment]
I think this should use Chef::Log instead of the log resource.  As for the level debug may make sense.

**Comment by MarkGibbons** [comment]
Fixed by #551. Please reopen if this change doesn't address your issue.
