### ISSUE TITLE
Option to specify nginx version using resource-based install

### ISSUE THREAD

**Issue by Dragsbaek** [sous-chefs/nginx#561]
## :person_frowning: Problem Statement

Unable to specify nginx version. 

Using nginx_install with passenger currently installs nginx v1.14.0, which has security issues.

```
nginx_install 'default' do
  ohai_plugin_enabled                   true
  source                                'passenger'
  version                               '1.18.0'
  default_site_enabled                  false
  group                                 'deploy'
  passenger_root                        '/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini'
  passenger_ruby                        "/usr/local/rvm/rubies/ruby-#{node['rvm']['version']}/bin/ruby"
  passenger_max_pool_size               6
  passenger_spawn_method                'smart'
  passenger_buffer_response             'off'
  passenger_min_instances               1
  passenger_max_instances_per_app       0
  passenger_pool_idle_time              300
  passenger_max_requests                0
  passenger_show_version_in_header      'on'
end
```

## :grey_question: Possible Solution

Add attribute for nginx_version

**Comment by ramereth** [comment]
@Dragsbaek please feel free to create a PR which addresses this issue and we'll work on getting it merged and released.

**Comment by bmhughes** [comment]
@Dragsbaek This is supported on v11 by overriding the packages to install with a version constraint depending on the package resource used (ie `'nginx > 1.18'`). There is also a `packages_versions` property added with #567 to specify them separately.
