### ISSUE TITLE
Configurable file/directory mode

### ISSUE THREAD

**Issue by limitusus** [sous-chefs/nginx#570]
### :speaking_head: Foreword

I would like the logged-in users to be able to read nginx config files and logs.

## :person_frowning: Problem Statement

This cookbook always creates log directories with 0750 and config files with 0640, so non-administrative users cannot read them.

## :grey_question: Possible Solution

File/directory mode 0750 and 0640 be the default, but I would be happy if they're configurable.

## :arrow_heading_up: Describe alternatives you've considered

`edit_resource` method can override modes, but it does not seem the best.

## :heavy_plus_sign: Additional context

N/A

**Comment by bmhughes** [comment]
Shouldn't be too difficult, I'll take a look into it.
