### ISSUE TITLE
nginx_site resource ignores the variables

### ISSUE THREAD

**Issue by axl89** [sous-chefs/nginx#574]
## :ghost: Brief Description

By following the [nginx_site resource docs](https://github.com/sous-chefs/nginx/blob/2691213fc692bac8500fe5c2b22e4729c95295ac/documentation/nginx_site.md) the NGINX site is indeed created but ignores the variables set.

## :pancakes: Cookbook version

11.3.0

## :woman_cook:  Chef-Infra Version

16.9.20

## :tophat: Platform details

Dokken Ubuntu 20.04

## Steps To Reproduce

Create a recipe as follows:

```ruby
 nginx_site 'test_site' do
   variables(
     'port': 80,
     'server_name': 'test_site',
     'default_root': '/var/www/nginx-default',
     'nginx_log_dir': '/var/log/nginx'
   )
   action :create
   owner 'root'
   mode '777'
   notifies :reload, 'nginx_service[nginx]', :delayed
 end

```

And the relevant output will show:

```
  * nginx_site[test_site] action create
    * template[/etc/nginx/conf.http.d/test_site.conf] action create
      - create new file /etc/nginx/conf.http.d/test_site.conf
      - update content in file /etc/nginx/conf.http.d/test_site.conf from none to efc72f
      --- /etc/nginx/conf.http.d/test_site.conf	2021-02-25 14:05:54.337658603 +0000
      +++ /etc/nginx/conf.http.d/.chef-test_site20210225-55-1tfah50.conf	2021-02-25 14:05:54.337658603 +0000
      @@ -1 +1,7 @@
      +# Generated by Chef for dokken
      +# Do NOT modify this file by hand.
      +#
      +
      +
      +
      - change mode from '' to '0777'
      - change owner from '' to 'root'
      - change group from '' to 'www-data'
```

ignoring the specified variables (e.g. `port`)

## :police_car: Expected behavior

The site should make use of the passed variables.

**Comment by axl89** [comment]
My bad, I've just realized that I did not include the `template` parameter. Maybe it'd be good to set it to `default-site.erb` as default? :)

Anyway, feel free to close this issue.

**Comment by bmhughes** [comment]
Ok just had a quite look and it seems that the docs are wrong, I'll get an update in. You'll have to reference the default [site-template](https://github.com/sous-chefs/nginx/blob/master/templates/default/site-template.erb) in the mean time to get the correct hash keys.

The expectation was that people would override the template used for their use case so the default template is very loose, looks like that example resource was carried over from < v11 and was missed.
