### ISSUE TITLE
`options` key has to be present if `upstream` is used in nginx_site

### ISSUE THREAD

**Issue by Fuuzetsu** [sous-chefs/nginx#584]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When using `nginx_site` resource, if we specify `upstream`, we are also forced to specify `options` key.

## :pancakes: Cookbook version

12.0.0

## :woman_cook:  Chef-Infra Version

16.13.16

## :tophat: Platform details

EC2 via kitchen test

## Steps To Reproduce

```ruby
nginx_site 'foo' do
  mode '0644'
  variables(
    'upstream' => {
      'server' => 'localhost:1234'
    }
  )
  action :create
end
```

## :police_car: Expected behavior

I expected a block like
```
upstream foo {
  server localhost:1234
}
```

## :heavy_plus_sign: Additional context

One can work around this by setting `'options' => []` but it's annoying and not documented.

https://github.com/sous-chefs/nginx/blob/433fe848a9ee2d54736d4d7255fb2e8b432f83e4/templates/default/site-template.erb#L22

**Comment by bmhughes** [comment]
PR incoming to fix the required options key but that hash format is still incorrect for the template, as it supports multiple upstreams and upstreams require a name then the configuration must be contained within a hash where the key is the name of the upstream like so.

```ruby
nginx_site 'foo' do
  mode '0644'
  variables(
    'upstream' => {
      'bar' => {
        'server' => 'localhost:1234',
      },
    }
  )
  action :create
end
```

**Comment by Fuuzetsu** [comment]
Thanks! You're right about the name bit of course, it was an oversight on my part.
